networks:
  nocobase-dev:

services:
  nocobase-dev:
    build:
      context: .
    container_name: nocobase-dev
    restart: on-failure
    init: true
    volumes:
      - ./projects:/projects
      - /etc/localtime:/etc/localtime:ro
      - ./ssh:/root/.ssh
    tty: true

  mysql:
    image: mysql:8.0.40
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
